apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: fastapi-ml
  labels:
    app: fastapi-ml
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi-ml
  template:
    metadata:
      name: fastapi-ml
      labels:
        app: fastapi-ml
    spec:
      containers:
        - image: ioiein/online_inference:v4
          name: fastapi-ml
          ports:
            - containerPort: 8000